#!/usr/bin/env node
/**
 * scripts/analyze-report.js
 *
 * Reads the Playwright JSON report from reports/test-results.json and
 * uses the ReportAnalyzerAgent to produce an AI-written executive summary.
 *
 * Usage:
 *   # Run tests first to generate the report
 *   npx playwright test --reporter=json
 *
 *   # Then analyse
 *   OPENAI_API_KEY=sk-ant-... node scripts/analyze-report.js
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { resolve } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';
import * as dotenv from 'dotenv';
dotenv.config();

const __dirname = dirname(fileURLToPath(import.meta.url));

import { ReportAnalyzerAgent } from '../agents/ReportAnalyzerAgent.js';

async function main() {
  const reportPath = resolve(__dirname, '../reports/test-results.json');

  if (!existsSync(reportPath)) {
    console.error(
      `\n  Report not found at ${reportPath}\n` +
      '   Run the tests first: npx playwright test --reporter=json\n'
    );
    process.exit(1);
  }

  if (!process.env.OPENAI_API_KEY) {
    console.error('\n OPENAI_API_KEY is not set.\n');
    process.exit(1);
  }

  console.log('\n ReportAnalyzerAgent — Reading test results...\n');

  const report = JSON.parse(readFileSync(reportPath, 'utf-8'));
  const agent  = new ReportAnalyzerAgent();
  const summary = await agent.analyze(report);

  if (!summary) {
    console.error('Agent returned no summary.');
    process.exit(1);
  }

  // Print to console
  console.log('\n' + '═'.repeat(60));
  console.log('  AI TEST REPORT SUMMARY');
  console.log('═'.repeat(60) + '\n');
  console.log(summary);
  console.log('\n' + '═'.repeat(60) + '\n');

  // Save to file
  const outDir  = resolve(__dirname, '../reports');
  const outFile = resolve(outDir, 'ai-summary.md');
  mkdirSync(outDir, { recursive: true });

  const content = `# AI Test Report Summary\n\n_Generated by ReportAnalyzerAgent_\n\n${summary}\n`;
  writeFileSync(outFile, content);

  console.log(` Summary saved to: ${outFile}\n`);
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
